### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by KingOfGerrit** [hippymulehead/RAMiniVector#1]
Memory leak in destructor: `virtual ~RAMiniVector() {free(d_data);};`
If you put objects in container, and delete container, destructor of objects don't call.
Please, use `new []` and `delete []`.

**Comment by hippymulehead** [comment]
New version coming soon.  There was more wrong than just this.  New version profiles clean, is faster, still compiles on Arduino

**Comment by hippymulehead** [comment]
Sorry I didn't get back to this but as for uses on Arduino, most would never call the destructor so as for how bad the bug was, it was pretty low on the radar.
